.\"
." Copyright (c) 2010, Mark Bucciarelli <mark@crosscutmedia.com>
." 
." Permission to use, copy, modify, and/or distribute this software for any
." purpose with or without fee is hereby granted, provided that the above
." copyright notice and this permission notice appear in all copies.
." 
." THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
." WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
." MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
." ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
." WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
." ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
." OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
." 
.\"
.\"

.Dd August 13, 2010
.Dt EBSCP 1
.Os
.
.Sh NAME
.Nm ebscp
.Nd copy data to a Trac resource.
.Sh SYNOPSIS
.Nm ebscp
.Ar data
.Ar resource
.Sh DESCRIPTION
Copy the given 
.Ar data 
to the given 
.Ar resource .
For example, to book time to a ticket, 
.Ar data
would be the number of hours you worked, and the
.Ar resource
would be the ticket.  (See EXAMPLES section below for a specific example.)
.Pp
If the copy succeeds, the output of
.Nm
is OK.
.Pp
For ticket resources, you must be the owner of the ticket.
.Pp
The supported resources are:
.Ss ticket/<ticket_number>/estimate
.Pp
Estimate how many hours it will take you to finish 
.Ar ticket_number .
.Pp
A new estimate overwrites the previous estimate.
.Ss ticket/<ticket_number>/hours/[YYYY-MM-DD]
.Pp
Book hours worked to
.Ar ticket_number .
.Pp
New hours do not overwrite previous hours, but are added to the total.
Negative hours are allowed.
.Pp
In order to book hours, the ticket must have an estimate.
.Pp
By default, hours are booked for today.  If you want to book time that
you worked on a previous day, use the optional
.Ar YYYY-MM-DD
argument.
.Ss ticket/<ticket_number>/minutes/[YYYY-MM-DD]
.Pp
Same as previous resource, but book the number of minutes to the
ticket.  The minutes are converted to hours and posted to the ticket.
.Ss ticket/<ticket_number>/status
.Pp
Change a ticket's status.  For this resource,
.Ar data
can either be 
.Dq closed
or 
.Dq reopened .
.Sh EXAMPLES
.Pp
Add 15 minutes to your total hours worked on ticket number 10.
.Pp
.Dl $ ebscp .25 ticket/10/hours
.Dl OK$ 
.Pp
Close ticket 15.
.Pp
.Dl $ ebscp closed ticket/15/status
.Dl OK$ 
.Sh SEE ALSO
.Xr ebsls 5
.Xr ebsconf 5
.Rs
.%A Joel Spolsky
.%T "Evidence Based Scheduling"
.%J "http://www.joelonsoftware.com/items/2007/10/26.html"
.%D 2007
.Re
