.\"
." Copyright (c) 2010, Mark Bucciarelli <mark@crosscutmedia.com>
." 
." Permission to use, copy, modify, and/or distribute this software for any
." purpose with or without fee is hereby granted, provided that the above
." copyright notice and this permission notice appear in all copies.
." 
." THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
." WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
." MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
." ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
." WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
." ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
." OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
." 
." NOTE: to test, $cat ebsls.1 | man -l -
.\"

.Dd August 13, 2010
.Dt EBSLS 1
.Os
.
.Sh NAME
.Nm ebsls
.Nd list contents of an evidence-based scheduling resource in Trac
.Sh SYNOPSIS
.Nm ebsls
.Ar resource
.Sh DESCRIPTION
The output of
.Nm
depends on the
.Ar resource
specified.
.Pp
The supported resources are listed below.
.Ss tickets
.Pp
List the tickets you own in Trac in order of priority (then ticket number).
.Pp
Only tickets with a status not equal to 
.Dq closed
are listed.
Each row has the following space-delimited columns:
.Pp
.Bl -enum -offset indent -compact
.It 
ticket id
.It 
ticket summary
.El
.Ss fulltickets
.Pp
The id, summary, expected hours, actual hours, status and description
are printed out for each ticket you own that has a status other than
.Dq closed .
.Ss log
.Pp
One row for time you posted time to a ticket.
Each row has the following tab-delimited columns:
.Pp
.Bl -enum -offset indent -compact
.It 
ticket id
.It 
the date and time you logged the entry
.It 
hours worked
.El
.Sh EXAMPLES
List your open tickets:
.Pp
.Dl $ ebsls tickets
.Dl https://www.example.com/trac/ebs/mark/tickets:
.Dl   593  API
.Dl   690  SQL for Reporting
.Dl   779  Get images to dev box.
.Dl   848  testing ebs posting
.Dl $
.Sh BUGS
When listing the log, the date of the hours worked is always the date
you posted the entry, and thus does not take into account the optional
.Ar YYYY-MM-DD
argument that 
.Nm ebscp 
takes.  The date stored in Trac does record that optional date, it 
is just not used by 
.Nm .
.Sh SEE ALSO
.Xr ebscp 1
.Xr ebsconf 5
.Rs
.%A Joel Spolsky
.%T "Evidence Based Scheduling"
.%J "http://www.joelonsoftware.com/items/2007/10/26.html"
.%D 2007
.Re
